name: CI - Configure, Build, Test

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    if: "!contains(github.event.head_commit.message, 'skip build')"
    runs-on: self-ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure the Build System
        run: |
          cmake --preset default
          tree build/default

      - name: Build the Project
        run: |
          cmake --build --preset default

      - name: Run Tests
        run: |
          ctest --preset default

      - name: Package the application
        run: |
          cmake --build --preset default -t package

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: archive-self-ubuntu-24.04
          path: |
            build/default/*.tar.gz

  build-docker:
    needs: build-test
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
         
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: reponame
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}          

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.reponame.outputs.lowercase }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}        

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-apptainer:
    runs-on: self-apptainer
    needs: build-docker
    env:
      apptainer: /opt/apptainer/v1.4.0/apptainer/bin/apptainer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: reponame
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}       

      - name: Login to GitHub Container Registry
        run: |
          ${{ env.apptainer }} remote login -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_PAT }} oras://ghcr.io

      - name: Convert Docker Image to Apptainer SIF
        run: |
          echo ${{ needs.build-docker.outputs.tags }}
          # Set the SIF filename based on the repository name.
          sif=$(basename ${{ steps.reponame.outputs.lowercase }}.sif)
          # Pull the Docker image (tagged as 'solution') and convert it to a SIF file.
          ${{ env.apptainer }} pull -F $sif docker://${{ needs.build-docker.outputs.tags }}
          # Inspect the SIF file to verify its contents.
          ${{ env.apptainer }} inspect $sif

      - name: Upload Apptainer SIF to GitHub Container Registry
        run: |
          # Determine the SIF filename.
          sif=$(basename ${{ steps.reponame.outputs.lowercase }}.sif)
          # Push the SIF file to GHCR under the tag 'solution-sif'
          ${{ env.apptainer }} push $sif oras://ghcr.io/${{ needs.build-docker.outputs.tags }}-sif

      - name: Deploy
        run: |
          gh workflow -R coe-hidalgo2/202503-c3b-dandaKrpelik run deploy.yml -r main -f image=${{ needs.build-docker.outputs.tags }}-sif
