name: DEBUG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  print:
    runs-on: self-ubuntu-24.04
    steps:
      - run: echo ${{ github.repository }}
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - run: echo ${{ steps.string.outputs.lowercase }}
